export const RO_COUNTY = [
  { name: "Alba", code: "01" },
  { name: "Arad", code: "02" },
  { name: "Argeș", code: "03" },
  { name: "Bacău", code: "04" },
  { name: "Bihor", code: "05" },
  { name: "Bistrița-Năsăud", code: "06" },
  { name: "Botoșani", code: "07" },
  { name: "Brașov", code: "08" },
  { name: "Brăila", code: "09" },
  { name: "Buzău", code: "10" },
  { name: "Caraș-Severin", code: "11" },
  { name: "Cluj", code: "12" },
  { name: "Constanța", code: "13" },
  { name: "Covasna", code: "14" },
  { name: "Dâmbovița", code: "15" },
  { name: "Dolj", code: "16" },
  { name: "Galați", code: "17" },
  { name: "Gorj", code: "18" },
  { name: "Harghita", code: "19" },
  { name: "Hunedoara", code: "20" },
  { name: "Ialomița", code: "21" },
  { name: "Iași", code: "22" },
  { name: "Ilfov", code: "23" },
  { name: "Maramureș", code: "24" },
  { name: "Mehedinți", code: "25" },
  { name: "Mureș", code: "26" },
  { name: "Neamț", code: "27" },
  { name: "Olt", code: "28" },
  { name: "Prahova", code: "29" },
  { name: "Satu Mare", code: "30" },
  { name: "Sălaj", code: "31" },
  { name: "Sibiu", code: "32" },
  { name: "Suceava", code: "33" },
  { name: "Teleorman", code: "34" },
  { name: "Timiș", code: "35" },
  { name: "Tulcea", code: "36" },
  { name: "Vaslui", code: "37" },
  { name: "Vâlcea", code: "38" },
  { name: "Vrancea", code: "39" },
  { name: "București", code: "40" },
  { name: "București - Sector 1", code: "41" },
  { name: "București - Sector 2", code: "42" },
  { name: "București - Sector 3", code: "43" },
  { name: "București - Sector 4", code: "44" },
  { name: "București - Sector 5", code: "45" },
  { name: "București - Sector 6", code: "46" },
  { name: "Călărași", code: "51" },
  { name: "Giurgiu", code: "52" },
];
